name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
  workflow_dispatch:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # required for all workflows
      security-events: write
      # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      actions: read
      checks: write
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Node Dependencies
        run: |
          npm ci
        env:
          CI: TRUE

      - name: Run ESLint Json
        run: npx ng lint
          --format json
          --output-file eslint_report.json
          --silent
          --quiet
        continue-on-error: true

      - name: Annotate Code
        uses: DerLev/eslint-annotations@v2
        with:
          error-on-warn: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          eslint-report: eslint_report.json
